version: 2

jobs:
  build:
    working_directory: ~/brdr-log

    docker:
      - image: circleci/node:7.10.0

    # branches:
    #   only:
    #     - master

    steps:
      - checkout

      - restore_cache:
          keys:
            - brdr-log-{{ checksum "theme/package.json" }}

      - run:
          name: Install Node Package
          command: |
            cd theme
            npm install

      - save_cache:
          key: brdr-log-{{ checksum "theme/package.json" }}
          paths:
            - ./theme/node_modules

      - run:
          name: Test
          command: |
            cd theme
            npm run lint

      - run:
          name: Build
          command: |
            cd theme
            npm run build
